title: My first web site

description: >
  My first attempt at creating a website

author:
  name: BK Gilroy
  email: your-email@domain.com

nav_pages:
  - about.md
  - contact.md

max-width: 800px

show_excerpts: true
show_rss_feed: true
show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

content_selector: div.post-content,div.home
